config/routes.rb
Rails.application.routes.draw do
  get  'paginas/home'

   root 'paginas#home'
  get 'about' => 'paginas#about'
  get 'yo' => 'paginas#yo'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/views/layouts/_carrucel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox" >

    <div class="item active" >
      <%= image_tag "piola.gif" %>
      <div class="carousel-caption">
      </div>
    </div>

    <div class="item" >
        <%= image_tag "fin.gif" %>
      <div class="carousel-caption">

      </div>
    </div>

    <div class="item">
      <%= image_tag "estrellas" %>
      <div class="carousel-caption">

      </div>
    </div>


  </div>


</div>

app/views/layouts/_footer.html.erb


<nav aria-label="..." class="center">
  <ul class="pagination">
    <li class="active"><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
    <li class="active"><%= link_to '1', "#" %> </li>
    <li class="active"><%= link_to '2', "#" %>  </a></li>

  </ul>
</nav>



<footer class="bs-docs-footer">
<div class="container">


  <ul class="bs-docs-footer-links">
    <li> <a href="https://www.instagram.com/josue_d_urban/">instagram</a></li>
    <li><a href="https://www.facebook.com/josue.u.crew">facebook</a></li>
    <li><a href="https://www.tumblr.com/blog/music-smiles-you">tumblr</a></li>
</ul>

<p> By Josue Urban  </p>

</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
<div class="container"> <!--alig el nav bar-->
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'Alis', root_path, class:'navbar-brand'%>

  </div>


<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">  <!--PERMITE ENCONDER LA LISTA EN UNA BARRA-->

    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Inicio", root_path %></li>
        <li><%= link_to "Nosotros", about_path %></li>
            <li><%= link_to "Yo", yo_path %></li>
        </ul>
      </li>

  </div><!-- /.navbar-collapse -->
</div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1"> <!--sirve para q al abrir la app en un mobil mejore la resolucion response -->
  <%= render 'layouts/header'%> <!--  llamnamos nuetro archivo parcial  -->
</head>
<body>




<div class="container">
  <%= yield %>

</div>





</body>
</html>

app/views/paginas/about.html.erb
<h1>Acerca de nosotros<h1/>
  <p>Estamos trabajando en esta aplicacion..... xD </p>
  <p> Lento pero seguro ;) <p/>





<br>
</br>

  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
          <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            OBJETIVOS
          </a>
        </h4>
      </div>
      <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
           .-. No hay objetivos en esta empresa :v

        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingTwo">
        <h4 class="panel-title">
          <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              MISION
          </a>
        </h4>
      </div>
      <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
        <div class="panel-body">
          >.< Si sabes que no hay objetivos, por que habria una mision xD
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingThree">
        <h4 class="panel-title">
          <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            VISION
          </a>
        </h4>
      </div>
      <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
        <div class="panel-body">
           Es mas que logico que aca no habria nada :v
        </div>
      </div>
    </div>
  </div>




<div class="center">
<%= image_tag "bart.gif"%>
</div>

app/views/paginas/home.html.erb
<div class="container">
<div  class="jumbotron center">
<h1>  Welcome on Board  ;)</h1>
    <%= image_tag "logo.png" %>
</div>
</div>



<div class="container" class="row">


<div class="center">
  <%= image_tag "lol.jpg",  :width=>400, :height=>300 %>
</div>

</div>


<br>
</br>

<div class="row" >
  <div class="container">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag "estrellas.gif", :width=>234, :height=>304 %>


      <div class="caption center">
        <h3>Pienso...</h3>
        <p>Me pregunto si las estrellas se iluminan con el fin de que algun día, cada uno pueda encontrar la suya.</p>

      </div>

    </div>
  </div>


    <div class="col-sm-6 col-md-4">
      <div class="thumbnail ">
        <%= image_tag "yo.jpg", :width=>234, :height=>304 %>

        <div class="caption center">
          <h3>Siento...</h3>
          <p>No me atreveria a navegar por el mar de tus miradas, se que me hundiria.</p>
        </div>

      </div>
    </div>


    <div class="col-sm-6 col-md-4">
      <div class="thumbnail ">
            <%= image_tag "smile.gif", :width=>234, :height=>304 %>

        <div class="caption center">
          <h3>Digo...</h3>
          <p>Sus pasos mis latidos, mientras mas lejos estas mas lento el corazon va...</p>
        </div>

      </div>
    </div>

</div> <!-- contenedor     -->
</div>

<div class="center">
  <%= image_tag "piola.gif", :width=>500, :height=>100  %>
</div>



<footer >

<%= render 'layouts/footer'%>


</footer>

app/views/paginas/yo.html.erb
<body class="bg">

</body>